include: package:lint/strict.yaml

analyzer:
  exclude:
    - build/**
    - "**/generated_plugin_registrant.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/i18n/messages*.dart"
  language:
    strict-casts: true
    strict-raw-types: false
  errors:
    todo: ignore

linter:
  rules:
    always_use_package_imports: true
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    constant_identifier_names: false
    prefer_function_declarations_over_variables: false
    prefer_single_quotes: true
    sort_constructors_first: true
    unawaited_futures: true
    use_super_parameters: true
